Repository Gbury/dolmen, pull requests merged in 2023-06, with the labels that each got.

#156 Add convenience State.update and State.update_opt
  CHANGES.md
  src/loop/state.ml
  src/standard/hmap.ml
  src/standard/hmap.mli
Labels: enhancement

#157 Add printing of type definitions in debug output
  CHANGES.md
  src/interface/term.ml
  src/interface/ty.ml
  src/loop/expr_intf.ml
  src/loop/typer.ml
  src/loop/typer.mli
  src/loop/typer_intf.ml
  src/model/loop.ml
  src/standard/expr.ml
  src/standard/expr.mli
  src/typecheck/intf.ml
  src/typecheck/tff.ml
  src/typecheck/tff.mli
  src/typecheck/tff_intf.ml
  src/typecheck/thf.ml
  src/typecheck/thf.mli
  src/typecheck/thf_intf.ml
Labels: enhancement

#154 Implement best mode for model verification
  doc/tuto.md
  src/bin/hints.ml
  src/bin/options.ml
  src/loop/typer.ml
  src/loop/typer.mli
  src/loop/typer_intf.ml
  src/model/loop.ml
  src/model/model.ml
  src/model/model.mli
  src/standard/loc.ml
  src/standard/loc.mli
  src/typecheck/float.ml
  src/typecheck/logic.ml
  src/typecheck/logic.mli
  tests/model/error/missing_answer.expected
  tests/model/funs/dune
  tests/model/funs/fun_3.expected
  tests/model/funs/fun_3.smt2
  tests/model/funs/out_of_order.expected
  tests/model/funs/out_of_order.rsmt2
  tests/model/funs/out_of_order.smt2
  tests/model/int/div_zero_out_of_order.expected
  tests/model/int/div_zero_out_of_order.rsmt2
  tests/model/int/div_zero_out_of_order.smt2
  tests/model/int/dune
  tests/model/int/out_of_order2.expected
  tests/model/int/out_of_order2.rsmt2
  tests/model/int/out_of_order2.smt2
  tests/model/interleaved/dune
  tests/model/interleaved/flags.dune
  tests/model/interleaved/out_of_order.expected
  tests/model/interleaved/out_of_order2.expected
Labels: enhancement

#155 Fix reason for reserved builtins
  CHANGES.md
  src/loop/typer.ml
  src/typecheck/arith.ml
  src/typecheck/core.ml
  src/typecheck/float.ml
  src/typecheck/intf.ml
  src/typecheck/thf.ml
  tests/model/funs/dune
  tests/model/funs/reserved.expected
  tests/model/funs/reserved.rsmt2
  tests/model/funs/reserved.smt2
  tests/typing/warnings/shadow/reserved_const.expected
Labels: bugfix

#136 Support more Bit-Vector primitives in Alt-Ergo's native language
  src/interface/term.ml
  src/loop/typer.ml
  src/typecheck/bitv.ml
  src/typecheck/bitv.mli
Labels: new feature

#140 Support check_sat statement for Alt-Ergo language
  doc/tuto.md
  src/interface/stmt.ml
  src/languages/ae/ast.ml
  src/languages/ae/lexer.mll
  src/languages/ae/parser.mly
  src/languages/ae/syntax.messages
  src/languages/ae/tokens.mly
  src/languages/smtlib2/poly/ast.ml
  src/loop/typer.ml
  src/loop/typer_intf.ml
  src/model/loop.ml
  src/standard/statement.ml
  src/standard/statement.mli
  tests/parsing/ae/pass/dune
  tests/parsing/ae/pass/test-check-sat_1.ae
  tests/parsing/ae/pass/test-check-sat_1.expected
Labels: new feature
